name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Dependencies
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.1.6

  # File and Printing
  open_file: ^3.5.10
  printing: ^5.10.0
  path_provider: ^2.1.5

  # PDF and Views
  flutter_pdfview: ^1.3.4
  pdf: ^3.11.0

  # UI and Animations
  flutter_animate: ^4.5.2
  syncfusion_flutter_charts: ^28.1.36
  syncfusion_flutter_datepicker: ^28.1.36
  fl_chart: ^0.70.0

  # Internationalization
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
